language: java

dist: trusty
jdk:
  - oraclejdk9
addons:
  apt:
    packages:
    - junit4
    - libmockito-java
script:
  - rm -r bin/*.class bin/*.exec bin/reportDir 2> /dev/null || true
  - mkdir -p bin
  - javac -classpath /usr/share/java/junit4.jar:/usr/share/java/mockito-core.jar PriorityQueueTest.java -d bin
  - cd bin
  - java -classpath .:/usr/share/java/junit4.jar:/usr/share/java/mockito-core.jar PriorityQueueTest
